[package]
name = "ggrs"
version = "0.2.1"
authors = ["Georg Schuppe <georg.schuppe@gmail.com>"]
edition = "2018"
description = "GGRS (good game rollback system) is a reimagination of the GGPO network SDK"
license = "MIT"
readme = "README.md"
repository = "https://github.com/gschup/ggrs"
homepage = "https://github.com/gschup/ggrs"
keywords = ["gamedev", "networking"]
categories = ["network-programming", "game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
bitfield-rle = "0.2"
parking_lot = "0.11"

[dev-dependencies]
adler = "1.0"
serial_test = "0.5"
sdl2 = { version = "0.34.5", features = ["bundled", "static-link"] }

# Examples
[[example]]
name = "box_game"
path = "examples/box_game/box_game.rs"

[[example]]
name = "box_game_spectator"
path = "examples/box_game/box_game_spectator.rs"

[[example]]
name = "box_game_synctest"
path = "examples/box_game/box_game_synctest.rs"
